name: Upload APK

on:
  push:
    branches:
      - main
    paths:
      - '**/v6*.apk'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "main"
      
      - name: Get APK files
        run: |          
          apk_files=$(find . -name "*v6*.apk")
          echo "APK_FILES=$apk_files" >> $GITHUB_ENV
          echo "Current directory: $(pwd)"
          echo "Workspace directory: $GITHUB_WORKSPACE"
          echo "Found APK files: $apk_files"
          echo "APK_FILES: ${{ env.APK_FILES }}"          

      - name: Extract version from APK file name
        run: |
          # 提取版本号，假设版本号格式是类似 "_v6.0.apk"
          version=$(echo ${{ env.APK_FILES }} | sed 's/.*_\(.*\).apk/\1/')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "VERSION: ${{ env.VERSION }}"

      - name: Wait for second file to be uploaded
        run: |
          while true
          do
            # 根据版本号和v7查找文件
            new_apk_files=$(find . -name "*v7*${{ env.VERSION }}*.apk")
            if [ -n "$new_apk_files" ]; then
              echo "NEW_APK_FILES=$new_apk_files" >> $GITHUB_ENV
              break
            fi
            echo "Waiting for v7 APK with version ${VERSION},${{ env.VERSION }}..."
            sleep 10
          done

      - name: Update release tag
        run: |
          new_tag="${{ env.VERSION }}"
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Publish APK Releases
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          RELEASE_NAME: 'My App Release'
          RELEASE_DESCRIPTION: 'Automated APK release'
          DRAFT: false
          PRERELEASE: false
          TAG_NAME: ${{ env.NEW_TAG }}
        with:
          files: ${{ env.APK_FILES }} ${{ env.NEW_APK_FILES }}

      - name: Delete old APK files
        run: |
          old_apk_files=$(find . -name "*.apk" -not -name "*${{ env.VERSION }}*")
          if [ -n "$old_apk_files" ]; then
            rm -f $old_apk_files
          fi
