name: Upload APK

on:
  push:
    branches:
      - main
    paths:
      - '**/v6*.apk'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get APK files
        run: |          
          apk_files=$(find . -name "*v6*.apk" -exec stat -c '%Y %n' {} \; | sort -rn | head -1 | cut -d' ' -f2-)
          echo "APK_FILES=$apk_files" >> $GITHUB_ENV

      - name: Extract version from APK file name
        run: |
          # 提取版本号
          version=$(echo ${{ env.APK_FILES }} | sed 's/.*_\(.*\).apk/\1/')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Wait for second file to be uploaded
        run: |
          while true
          do
            # 根据版本号和v7查找文件
            new_apk_files=$(find . -name "*v7*${{ env.VERSION }}*.apk")
            if [ -n "$new_apk_files" ]; then
              echo "NEW_APK_FILES=$new_apk_files" >> $GITHUB_ENV
              break
            fi
            echo "Waiting for v7 APK with version ${VERSION}..."
            sleep 10
          done
      
      - name: Publish APK Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          RELEASE_NAME: 'My App Release'
          RELEASE_DESCRIPTION: 'Automated APK release'
          DRAFT: false
          PRERELEASE: false
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            ${{ env.APK_FILES }} 
            ${{ env.NEW_APK_FILES }}

      - name: Delete old APK files
        run: |
          old_apk_files=$(find . -name "*.apk" -not -name "*${{ env.VERSION }}*")
          if [ -n "$old_apk_files" ]; then
            rm -f $old_apk_files
            git config --global user.name "Kiritocyz"
            git config --global user.email "Kiritocyz@users.noreply.github.com"
            git add .
            git commit -m "Delete old APK files"
          fi
